CREATE DATABASE IF NOT EXISTS test_db;
USE test_db;

CREATE TABLE IF NOT EXISTS Customer (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(250) NOT NULL,
  password VARCHAR(150) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT NOW(),

  PRIMARY KEY(id)
);
